# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jekyll-Webpack Boilerplate
email: hi@allizad.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://allizad.com" # the base hostname & protocol for your site
twitter_username: allizad
github_username:  allizad

# Build settings
markdown: kramdown
source: src
destination: public


# Site settings
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: My New Jekyll Site
author: Your Name
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
keywords: # Keywords describing your site
- jekyll
- static site
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # your site's origin, e.g. https://forestry.io

exclude:
  - static-script.config.js
  - Gemfile
  - Gemfile.lock
  - config
  - scripts
  - LICENSE
  - node_modules
  - npm-debug.log
  - package.json
  - package-lock.json
  - README.md
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/