# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Examined!
email: nikita.a.novik@gmail.com
description: > # this means to ignore newlines until "baseurl:"
        We live our lives so they become Examined!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lifeexamined.github.io" # the base hostname & protocol for your site
twitter_username: examined13
github_username:  lifeexamined

#Permalink for Posts
permalink: /blog/:categories/:year/:month/:day/:title:output_ext

# Build settings
markdown: kramdown
